### PR TITLE
Update modules.rst

### PR DESCRIPTION
**Pull request by nh3**
This PR corrects inconsistencies in scanpy component names.

### CODE REVIEW

**Comment by pinin4fjords** [comment]
Thanks @nh3 ! Are doing any more docs PRs? I'm about to tag a release for @pcm32

**Comment by nh3** [comment]
I have more of an issue than a PR for the section "Writing wrapper scripts for R packages". In it, it recommends using `suppressPackageStartupMessages(require(package))` to load package. However, the recommended/widely accepted way of loading package outside a function is to use `library()` rather than `require()`, as the former stops execution with an error when the requested package fails to load (e.g. not available) whereas the latter keeps going with an warning. I know the code has been in our scripts for a while, which I can live with, but to put it as recommendations, I feel quite uneasy as it might incur unnecessary judgements. What do you think? @pinin4fjords @pcm32

**Comment by pinin4fjords** [comment]
I don't remember where that convention came from @nh3, but you reasoning seems sound, I'm happy for you to PR changes to that effect.

**Comment by nh3** [comment]
It's in the R manual. Just `?require`, it's explained under the "Details" section:

> Details:
> 
>      ‘library(package)’ and ‘require(package)’ both load the namespace
>      of the package with name ‘package’ and attach it on the search
>      list.  ‘require’ is designed for use inside other functions; it
>      returns ‘FALSE’ and gives a warning (rather than an error as
>      ‘library()’ does by default) if the package does not exist.

**Comment by pinin4fjords** [comment]
Yep, I get that, just didn't remember why I was using require ;-)

**Pull request merged**
